apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-appmgr-service
  labels:
    app: appmgr
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}  # Exposed service port
      targetPort: {{ .Values.service.httpPort }}  # Maps to containerPort
      protocol: TCP
    - name: rmrroute
      port: {{ .Values.service.rmrRoutePort }}
      targetPort: {{ .Values.service.rmrRoutePort }}
      protocol: TCP
    - name: rmrdata
      port: {{ .Values.service.rmrDataPort }}
      targetPort: {{ .Values.service.rmrDataPort }}
      protocol: TCP
  selector:
    app: appmgr
