apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-appmgr-service
  labels:
    app: appmgr
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: appmgr
  selector:
    app: appmgr
