replicaCount: 1

image:
  repository: docker.io/boing7898/ric-plt-xapp-frame-py
  pullPolicy: IfNotPresent
  tag: "latest" # Or use .Values.global.tag

service:
  type: ClusterIP
  port: 8080 # Or any port the xapp runner exposes

env:
  PYTHONUNBUFFERED: "0"
  PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: "python"
  RMR_SEED_RT: "/opt/ric/config/uta-rtg.rt"
  RMR_SRC_ID: "10.0.2.20"
  RMR_RTG_SVC: "" # leave empty, so RMR works correctly with RT Manager Simulator

volumeMounts:
  - name: routes-rtg
    mountPath: /opt/ric/config/uta-rtg.rt
    subPath: routes.rtg
  - name: script-volume
    mountPath: /opt/xApps/

volumes:
  - name: routes-rtg
    configMap:
      name: routes-rtg
  - name: script-volume
    configMap:
      name: {{ .Chart.Name }}-script

resources: {}
