replicaCount: 1

start:
  turbostat: true
  perf: true

image:
  repository: docker.io/boing7898/ric-plt-xapp-frame-py
  pullPolicy: Always
  tag: "latest" # Or use .Values.global.tag

service:
  type: ClusterIP
  port: 8080 # Or any port the xapp runner exposes

env:
  PYTHONUNBUFFERED: "0"
  PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: "python"
  RMR_SEED_RT: "/opt/ric/config/uta-rtg.rt"
  RMR_SRC_ID: "xapp-service"
  RMR_RTG_SVC: "4561" # leave empty, so RMR works correctly with RT Manager Simulator
  START_PERF: true
  START_TURBOSTAT: true

volumeMounts:
  - name: xapp-rtg
    mountPath: /opt/ric/config/uta-rtg.rt
    subPath: routes.rtg
  - name: script-volume
    mountPath: /opt/xApps/files/
  - mountPath: /mnt/data  # Mount path inside the container
    name: storage

volumes:
  - name: xapp-rtg
    configMap:
      name: xapp-rtg
  - name: script-volume
    configMap:
      name: xapp-script
  - name: storage
    persistentVolumeClaim:
      claimName: local-pvc  # This should match your PVC name
resources: {}
