apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: submgr
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: submgr
  template:
    metadata:
      labels:
        app: submgr
    spec:
      containers:
        - name: submgr
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          command: ["./submgr", "-f $CFG_FILE"]
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
          volumes:
            {{- toYaml .Values.volumes | nindent 8 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
