apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-submgr-service
  labels:
    app: submgr
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: submgr
  selector:
    app: submgr
