apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: submgr
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: submgr
    - port: 8088
      targetPort: 8088
      protocol: TCP
      name: subscription
  selector:
    app: submgr
