apiVersion: v1
kind: ConfigMap
metadata:
  name: submgr-config
data:
  submgr-config.yaml: |
    "local":
      "host": ":8088"
    "logger":
      "level": 3
    "rmr":
      "protPort" : "tcp:4560"
      "maxSize": 8192
      "numWorkers": 1
    "rtmgr":
      "hostAddr": "rtmgr-service"
      "port"    : "3800"
      "baseUrl" : "/ric/v1"
    "db":
      "sessionNamespace": "XMSession"
      "host": dbaas-service:6809"
      "prot": "tcp"
      "maxIdle": 80
      "maxActive": 12000
    "controls":
      "e2tSubReqTimeout_ms": 2000
      "e2tSubDelReqTime_ms": 2000
      "e2tRecvMsgTimeout_ms": 2000
      "e2tMaxSubReqTryCount": 2
      "e2tMaxSubDelReqTryCount": 2
      "checkE2State": "true"
      "readSubsFromDb": "true"
      "dbTryCount": 200
      "dbRetryForever": "true"
      "checkE2IEOrder": 1
