apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: e2term
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: e2term
  template:
    metadata:
      labels:
        app: e2term
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: e2term
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          securityContext:
              {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            - containerPort: {{ .Values.service.port }}
          command: ["/bin/sh", "-c"]
          args:
            - LOCAL_IP=$(hostname -I);
              sed -e s/@LOCAL_IP@/$LOCAL_IP/g
                  /tmp/config.conf | tee /opt/e2/config/config.conf;
              cat /opt/e2/config/config.conf;
              ./e2 -p config -f config.conf;
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
      serviceAccountName: e2term-service-account
