apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-e2term-deployment
  labels:
    app: e2term
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: e2term
  template:
    metadata:
      labels:
        app: e2term
    spec:
      containers:
        - name: e2term
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              protocol: SCTP
          command:
            - {{ .Values.command }}
          args: {{ .Values.args }}
          env:
            {{- range ,  := .Values.env }}
            - name: {{  }}
              value: {{  | quote }}
            {{- end }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
          volumes:
            {{- toYaml .Values.volumes | nindent 8 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
