apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-e2term-service
  labels:
    app: e2term
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: SCTP
      name: e2term
  selector:
    app: e2term
