apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: e2term
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 36421
      targetPort: 36421
      protocol: SCTP
      name: e2term1
    - port: 38000
      targetPort: 38000
      protocol: TCP
      name: e2term2
    - port: 4561
      targetPort: 4561
      protocol: TCP
      name: e2term3
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: e2term            
  selector:
    app: e2term
