apiVersion: v1
kind: ConfigMap
metadata:
  name: rtmgrcfg
data:
  rtmgr-config.yaml: |
    PlatformComponents:
      - name: "SUBMAN"
        fqdn: "{{ .Values.servicename.submgr.rmr }}"
        port: {{ .Values.serviceport.submgr.rmr.data }}
      - name: "E2MAN"
        fqdn: "{{ .Values.servicename.e2mgr.rmr }}"
        port: {{ .Values.serviceport.e2mgr.rmr.data }}

    XMURL: "http://{{ .Values.servicename.appmgr.http }}:{{ .Values.serviceport.appmgr.http }}/ric/v1/xapps"
    E2MURL: "http://{{ .Values.servicename.e2mgr.http }}:{{ .Values.serviceport.e2mgr.http }}/v1/e2t/list"
    RTFILE: "/db/rt.json"
    CFGFILE: "/cfg/rtmgr-config.yaml"
    RPE: "{{ .Values.rtmgr.rpe }}"
    SBI: "{{ .Values.rtmgr.sbi }}"
    SBIURL: "{{ .Values.rtmgr.sbiurl }}"
    NBI: "{{ .Values.rtmgr.nbi }}"
    NBIURL: "http://{{ .Values.servicename.rtmgr.http }}:{{ .Values.serviceport.rtmgr.http }}"
    SDL: "file"
    local:
      host: ":8080"
    logger:
      level: 4
    periodicRoutes:
      enable: true # or false, depending on your desired default
    rmr:
      protPort: "tcp:4560"
      maxSize: 1024
      numWorkers: 1
      threadType: 1
    subscription:
      host: "submgr-service:8080"

    messagetypes:
      - "RIC_HEALTH_CHECK_REQ=100"
      - "RIC_HEALTH_CHECK_RESP=101"
      - "RIC_ALARM=110"
      - "RIC_ALARM_QUERY=111"

    PlatformRoutes:
      - messagetype: 'RIC_SUB_REQ'
        senderendpoint: 'SUBMAN'
        subscriptionid: -1
        endpoint: ''
        meid: '%meid'
