apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: rtmgr
spec:
  type: ClusterIP
  ports:
    - port: 3800
      protocol: TCP
      name: "http"
      targetPort: 3800
    - port: 4561
      protocol: TCP
      targetPort: 4561
      name: "rmrroute"
    - port: 4560
      protocol: TCP
      targetPort: 4560
      name: "rmrdata"
  selector:
    app: rtmgr
