apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: rtmgr
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ "Values.serviceport.rtmgr.http" }}
      protocol: "TCP"
      name: "http"
      targetPort: "http"
    - port: {{ include "Values.serviceport.rtmgr.rmr.route" . }}
      protocol: TCP
      targetPort: "rmrroute"
      name: "rmrroute"
    - port: {{ include "Values.serviceport.rtmgr.rmr.data" . }}
      protocol: TCP
      targetPort: "rmrdata"
      name: "rmrdata"
  selector:
    app: rtmgr
