replicaCount: 1

image:
  repository: nexus3.o-ran-sc.org:10002/o-ran-sc/ric-plt-appmgr
  pullPolicy: IfNotPresent
  tag: "0.5.7" # Or use .Values.global.tag

env:
  CONTAINER_NAME: "ric_appmgr"
  HOST_NAME: "appmgr-service"
  POD_NAME: "appmgr_pod"
  SERVICE_NAME: "ric_appmgr_service"
  RMR_SEED_RT: "/opt/ric/config/router.txt"
  RMR_SRC_ID: "appmgr-service"
  DBAAS_SERVICE_HOST: dbaas-service

service:
  httpPort: 8080
  rmrRoutePort: 4560
  rmrDataPort: 4561

volumeMounts:
  - name: routes-rtg
    mountPath: /opt/ric/config/router.txt
    subPath: routes.rtg
  - name: appmgr-config
    mountPath: /opt/ric/config/appmgr.yaml
    subPath: appmgr.yaml

volumes:
  - name: routes-rtg
    configMap:
      name: routes-rtg
  - name: appmgr-config
    configMap:
      name: appmgr-config

resources: {}
