apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-lib-configmap
data:
  {{- range $path, $content := .Files.Glob "lib/*" }}
  {{ $path | base }}: |
    {{ $content | indent 4 }}
  {{- end }}
