apiVersion: v1
kind: ConfigMap
metadata:
  name: xapp-script
data:
  {{- $files := .Files }}
  {{- range tuple "xapp.py" "script2.py" }}
  {{ . }}: |-
    {{ $files.Get . | trim | indent 4 }}
  {{- end }}
  
  {{- $files := .Files.Glob "lib/*" }}
  {{- range $path, $file := $files }}
  {{ base $path }}: |
    {{ .Files.Get $path | nindent 8 }}
  {{- end }}
