apiVersion: v1
kind: ConfigMap
metadata:
  name: xapp-script
data:
  {{- $files := .Files }}
  {{- range tuple "xapp.py" "script2.py" }}
  {{ . }}: |-
{{ $files.Get . | trim | indent 4 }}
  {{- end }}
  {{- range $path, $bytes := .Files.Glob "lib/**" }}
  {{- if not (IsDir $path) }}
  {{ $path }}: |-
{{ $bytes | toString | trim | indent 4 }}
  {{- end }}
  {{- end }}
