apiVersion: v1
kind: ConfigMap
metadata:
  name: xapp-script
data:
  {{- $files := .Files }}
  {{- range tuple "xapp.py" "start-metrics.sh" }}
  {{ . }}: |-
{{ $files.Get . | trim | indent 4 }}
  {{- end }}
  {{- $root := . }}
  {{- range $f, $_ := .Files.Glob "lib/*" }}
    {{ base $f }}: |-
  {{ tpl ($root.Files.Get $f) $root | indent 4 }}
  {{- end }}
