apiVersion: v1
kind: ConfigMap
metadata:
  name: xapp-script
data:
  {{- $files := .Files }}
  
  # Including specific files in the root directory
  {{- range tuple "xapp.py" "script2.py" }}
  {{ . }}: |-
    {{ .Files.Get . | trim | indent 4 }}
  {{- end }}
  
  # Including all files inside the lib/ directory (recursively)
  {{- $libFiles := .Files.Glob "lib/**/*" }}
  {{- range $libFiles }}
  {{- $filePath := . }}
  {{ $baseName := base $filePath }}  # Extract the base name from the file path
  {{ $baseName }}: |
    {{ .Files.Get $filePath | nindent 8 }}  # Access the file content correctly
  {{- end }}
