apiVersion: v1
kind: ConfigMap
metadata:
  name: xapp-lib
data:
{{- $root := . }}
{{- range $f, $_ := .Files.Glob "lib/*" }}
  {{ base $f }}: |-
{{ tpl ($root.Files.Get $f) $root | indent 4 }}
{{- end }}
