apiVersion: v1
kind: ConfigMap
metadata:
  name: xapp-lib
data:
  {{- range $path, $_ := .Files.Glob "lib/*" }}
  {{ $path | trimPrefix "lib/" }}: |-
    {{ $.Files.Get $path | indent 4 }}
  {{- end }}
