apiVersion: v1
kind: ConfigMap
metadata:
  name: xapp-script
data:
  {{- $files := .Files }}
  
  # Including specific files in the root directory
  {{- range tuple "xapp.py" "script2.py" }}
  {{ . }}: |-
    {{ $files.Get . | trim | indent 4 }}
  {{- end }}

  # Including all files inside the lib/ directory
  {{- $libFiles := .Files.Glob "lib/*" }}
  {{- range $path, $file := $libFiles }}
  {{ base $path }}: |
    {{ .Files.Get $path | nindent 8 }}
  {{- end }}
