apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: python_xapp_runner
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: python_xapp_runner
  template:
    metadata:
      labels:
        app: python_xapp_runner
    spec:
      containers:
        - name: python-xapp-runner
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          command: [ "/bin/sh", "-c" ]
          args:
            - mkdir /tmp/xApp;
              cp -R /opt/xApps/* /tmp/xApp/;
              sleep 1000;
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          stdin: true
          tty: true
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
