apiVersion: v1
kind: Service
metadata:
  name: xapp-service
  labels:
    app: python_xapp_runner
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: python-xapp-runner
  selector:
    app: python_xapp_runner
