apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-python-xapp-runner-service
  labels:
    app: python_xapp_runner
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: python-xapp-runner
  selector:
    app: python_xapp_runner
