apiVersion: v1
kind: Service
metadata:
  name: xapp-service
  labels:
    app: python_xapp_runner
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 4560
      targetPort: 4560
      protocol: TCP
      name: rmr
    - port: 8090
      targetPort: 8090
      protocol: TCP
      name: http
  selector:
    app: python_xapp_runner
