apiVersion: v1
kind: ConfigMap
metadata:
  name: metrics-script
data:
  {{- $files := .Files }}
  {{- range tuple "xapp.py" "start-metrics.sh" }}
  {{ . }}: |-
{{ $files.Get . | trim | indent 4 }}
  {{- end }}
