apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: metrics-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: metrics-app
  template:
    metadata:
      labels:
        app: metrics-app
    spec:
      # --- Pod Level Settings ---
      {{ if .Values.waitgnb }} 
      initContainers:
        - name: init
          image: docker.io/oaisoftwarealliance/oai-tcpdump-init:alpine-3.20
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - until ncat -zvu srsran-5g-gtpu 2152; do echo "waiting for gNB to start"; sleep 1; done
          resources:
            requests:
              memory: 50Mi
              cpu: 1m
            limits:
              memory: 50Mi
              cpu: 1m
      {{ end }}

      containers:
        - name: python-xapp-runner
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            privileged: true          
          # --- Container Level Settings ---
          ports:
            - containerPort: {{ .Values.service.port }}
          command: [ "/bin/sh", "-c" ]
          args:
            - mkdir /tmp/xApp;
              cp -RL /opt/xApps/files/* /tmp/xApp/;
              cp -RL /opt/xApps/lib /tmp/xApp/;
              chmod +x /tmp/xApp/start-metrics.sh;
              exec python3 -u /tmp/xApp/xapp.py --log-level DEBUG --udp-port "${PORT}${RETINA_PORTS}" --bucket "${BUCKET}" --testbed "${TESTBED}" --db-config url="${URL}" org="${ORG}" token="${TOKEN}";
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          stdin: true
          tty: true

      # --- Pod Level Settings ---
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
