apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: dbaas
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: dbaas
  template:
    metadata:
      labels:
        app: dbaas
    spec:
      containers:
        - name: dbaas
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          command: [ "/bin/bash", "-c" ]
          args: 
           - exec redis-server --loadmodule /usr/local/libexec/redismodule/libredismodule.so
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
