apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-dbaas-deployment
  labels:
    app: dbaas
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: dbaas
  template:
    metadata:
      labels:
        app: dbaas
    spec:
      containers:
        - name: dbaas
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          command:
            - {{ .Values.command }}
          args: {{ .Values.args }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
