replicaCount: 1
waitgnb: false

image:
  repository: docker.io/boing7898/ric-plt-xapp-frame-py
  pullPolicy: Always
  tag: "latest" # Or use .Values.global.tag

service:
  type: ClusterIP
  port: 8080 # Or any port the xapp runner exposes

env:
  PYTHONUNBUFFERED: "0"
  PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: "python"
  RMR_SEED_RT: "/opt/ric/config/uta-rtg.rt"
  RMR_SRC_ID: "xapp-service"
  RMR_RTG_SVC: "4561" # leave empty, so RMR works correctly with RT Manager Simulator
  START_PERF: true
  START_TURBOSTAT: true
  PORT: 55555
  BUCKET: srsran
  TESTBED: default
  URL: http://influxdb2.srs72.svc.cluster.local:8086
  ORG: srs
  TOKEN: "605bc59413b7d5457d181ccf20f9fda15693f81b068d70396cc183081b264f3b"  

volumeMounts:
  - name: xapp-rtg
    mountPath: /opt/ric/config/uta-rtg.rt
    subPath: routes.rtg
  - name: script-volume
    mountPath: /opt/xApps/files/
  - mountPath: /mnt/data  # Mount path inside the container
    name: storage
  - name: cpu
    mountPath: /dev/cpu

volumes:
  - name: cpu
    hostPath:
      path: "/dev/cpu"
  - name: xapp-rtg
    configMap:
      name: xapp-rtg
  - name: script-volume
    configMap:
      name: xapp-script
  - name: storage
    persistentVolumeClaim:
      claimName: local-pvc  # This should match your PVC name
resources: {}
