apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: e2mgr
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: e2mgr
  template:
    metadata:
      labels:
        app: e2mgr
    spec:
      containers:
        - name: e2mgr
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["./main", "-port=3800", "-f", "/opt/E2Manager/resources/configuration.yaml"]
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
