apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-e2mgr-service
  labels:
    app: e2mgr
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: e2mgr
  selector:
    app: e2mgr
