apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: e2mgr
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 3800
      targetPort: 3800
      protocol: TCP
      name: e2mgr1
    - port: 3801
      targetPort: 3801
      protocol: TCP
      name: e2mgr2
    - port: 4561
      targetPort: 4561
      protocol: TCP
      name: e2mgr3  
  selector:
    app: e2mgr
